# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import device_service_pb2 as device__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in device_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceManagementStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterDevice = channel.unary_unary(
                '/device.DeviceManagement/RegisterDevice',
                request_serializer=device__service__pb2.RegisterDeviceRequest.SerializeToString,
                response_deserializer=device__service__pb2.RegisterDeviceResponse.FromString,
                _registered_method=True)
        self.SetDeviceStatus = channel.unary_unary(
                '/device.DeviceManagement/SetDeviceStatus',
                request_serializer=device__service__pb2.SetDeviceStatusRequest.SerializeToString,
                response_deserializer=device__service__pb2.SetDeviceStatusResponse.FromString,
                _registered_method=True)
        self.GetDeviceInfo = channel.unary_unary(
                '/device.DeviceManagement/GetDeviceInfo',
                request_serializer=device__service__pb2.GetDeviceInfoRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetDeviceInfoResponse.FromString,
                _registered_method=True)
        self.InitiateDeviceAction = channel.unary_unary(
                '/device.DeviceManagement/InitiateDeviceAction',
                request_serializer=device__service__pb2.InitiateDeviceActionRequest.SerializeToString,
                response_deserializer=device__service__pb2.InitiateDeviceActionResponse.FromString,
                _registered_method=True)
        self.GetDeviceActionStatus = channel.unary_unary(
                '/device.DeviceManagement/GetDeviceActionStatus',
                request_serializer=device__service__pb2.GetDeviceActionStatusRequest.SerializeToString,
                response_deserializer=device__service__pb2.GetDeviceActionStatusResponse.FromString,
                _registered_method=True)


class DeviceManagementServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDeviceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InitiateDeviceAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceActionStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterDevice,
                    request_deserializer=device__service__pb2.RegisterDeviceRequest.FromString,
                    response_serializer=device__service__pb2.RegisterDeviceResponse.SerializeToString,
            ),
            'SetDeviceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDeviceStatus,
                    request_deserializer=device__service__pb2.SetDeviceStatusRequest.FromString,
                    response_serializer=device__service__pb2.SetDeviceStatusResponse.SerializeToString,
            ),
            'GetDeviceInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInfo,
                    request_deserializer=device__service__pb2.GetDeviceInfoRequest.FromString,
                    response_serializer=device__service__pb2.GetDeviceInfoResponse.SerializeToString,
            ),
            'InitiateDeviceAction': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateDeviceAction,
                    request_deserializer=device__service__pb2.InitiateDeviceActionRequest.FromString,
                    response_serializer=device__service__pb2.InitiateDeviceActionResponse.SerializeToString,
            ),
            'GetDeviceActionStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceActionStatus,
                    request_deserializer=device__service__pb2.GetDeviceActionStatusRequest.FromString,
                    response_serializer=device__service__pb2.GetDeviceActionStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'device.DeviceManagement', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('device.DeviceManagement', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceManagement(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceManagement/RegisterDevice',
            device__service__pb2.RegisterDeviceRequest.SerializeToString,
            device__service__pb2.RegisterDeviceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetDeviceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceManagement/SetDeviceStatus',
            device__service__pb2.SetDeviceStatusRequest.SerializeToString,
            device__service__pb2.SetDeviceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceManagement/GetDeviceInfo',
            device__service__pb2.GetDeviceInfoRequest.SerializeToString,
            device__service__pb2.GetDeviceInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InitiateDeviceAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceManagement/InitiateDeviceAction',
            device__service__pb2.InitiateDeviceActionRequest.SerializeToString,
            device__service__pb2.InitiateDeviceActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDeviceActionStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/device.DeviceManagement/GetDeviceActionStatus',
            device__service__pb2.GetDeviceActionStatusRequest.SerializeToString,
            device__service__pb2.GetDeviceActionStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
